services:
  webapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./restapipj:/restapipj
    environment:
      - DB_HOST=database
      - DB_NAME=restapipjname
      - DB_USER=restapipjuser
      - DB_PASS=restapipjpass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=restapipjname
      - POSTGRES_USER=restapipjuser
      - POSTGRES_PASSWORD=restapipjpass