# Generated by Django 4.2.6 on 2023-10-20 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('guitar_article', models.PositiveIntegerField(unique=True, verbose_name='Артикул')),
                ('guitar_slug', models.SlugField(unique=True, verbose_name='URL')),
                ('guitar_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('guitar_price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Старая цена')),
                ('guitar_hit', models.BooleanField(default=False, verbose_name='Хит')),
                ('guitar_image', models.ImageField(upload_to='media/', verbose_name='Изображение для превью')),
                ('guitar_description', models.TextField(verbose_name='Описание')),
                ('guitar_date', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('guitar_draft', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Гитара',
                'verbose_name_plural': 'Гитары',
                'ordering': ['-guitar_date'],
            },
        ),
    ]
