# Generated by Django 4.2.6 on 2023-10-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('guitar_photo_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('guitar_photo_draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('guitar_photo_on_guitar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.guitar')),
            ],
            options={
                'verbose_name': 'Фото гитары',
                'verbose_name_plural': 'Фото гитары',
                'ordering': ['guitar_photo_draft'],
            },
        ),
        migrations.AddField(
            model_name='guitar',
            name='guitar_image_all',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.guitarphoto', verbose_name='Фото гитар'),
        ),
    ]
