# Generated by Django 4.2.6 on 2023-10-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_guitarphoto_guitar_guitar_image_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='guitar_image_all',
        ),
    ]
