# Generated by Django 4.2.6 on 2023-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_remove_guitar_guitar_image_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guitarphoto',
            options={'ordering': ['order'], 'verbose_name': 'Фото гитары', 'verbose_name_plural': 'Фото гитары'},
        ),
        migrations.RenameField(
            model_name='guitarphoto',
            old_name='guitar_photo_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='guitarphoto',
            old_name='guitar_photo_draft',
            new_name='pub',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='guitar_draft',
        ),
        migrations.AddField(
            model_name='guitar',
            name='guitar_pub',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='OG image'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='seo_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='SEO title'),
        ),
    ]
