# Generated by Django 4.2.6 on 2023-10-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_alter_guitarphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('pub', models.BooleanField(default=True, verbose_name='Публикация')),
                ('brand_name', models.CharField(max_length=80, verbose_name='Бренд')),
                ('brand_url', models.SlugField(unique=True, verbose_name='URL бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('pub', models.BooleanField(default=True, verbose_name='Публикация')),
                ('material_name', models.CharField(max_length=80, verbose_name='Материал')),
                ('material_url', models.SlugField(unique=True, verbose_name='URL материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('pub', models.BooleanField(default=True, verbose_name='Публикация')),
                ('count_string', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во струн')),
            ],
            options={
                'verbose_name': 'Струны',
                'verbose_name_plural': 'Струны',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TypeGuitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('pub', models.BooleanField(default=True, verbose_name='Публикация')),
                ('type_name', models.CharField(max_length=80, verbose_name='Название типа гитары')),
                ('type_url', models.SlugField(unique=True, verbose_name='URL типа')),
            ],
            options={
                'verbose_name': 'Тип гитары',
                'verbose_name_plural': 'Тип гитары',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubTypeGuitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('pub', models.BooleanField(default=True, verbose_name='Публикация')),
                ('sub_type_name', models.CharField(max_length=80, verbose_name='Название подтипа')),
                ('sub_type_url', models.SlugField(unique=True, verbose_name='URL подтипа')),
                ('sub_type_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.typeguitar', verbose_name='Типа')),
            ],
            options={
                'verbose_name': 'Тип гитары',
                'verbose_name_plural': 'Тип гитары',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuitarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.brand', verbose_name='Бренд')),
                ('guitar_category_on_guitar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.guitar')),
                ('guitar_category_sub_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.subtypeguitar', verbose_name='Вид')),
                ('guitar_category_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.typeguitar', verbose_name='Тип гитары')),
                ('guitar_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.material')),
                ('guitar_string', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.strings', verbose_name='Струны')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
